// C# Pills 15mg
// Copyright (C) 2021 Dust in the Wind
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;

namespace DustInTheWind.RandomToZero
{
    /// <summary>
    /// How likely it is that a specific number (for example zero) is generated by the Random instance?
    /// </summary>
    internal class Program
    {
        private static void Main(string[] args)
        {
            Generator generator = new();
            generator.BatchStart += HandleBatchStart;

            generator.Run();

            Console.WriteLine($"Number {generator.TargetNumber} was generated at index {generator.TargetNumberIndex:N0}.");

            // 1.385.893.022
            // 1.207.086.931
            //   223.735.804
            // 5.364.100.000
            // 2.768.044.585
            // 3.067.987.830
        }

        private static void HandleBatchStart(object sender, BatchStartEventArgs e)
        {
            Console.WriteLine($"Batch {e.BatchIndex:N0}");
        }
    }
}